version: '3.4'
services:
  rasa-flask:
    image: rasa-bot:latest
    build: "./"
    volumes: 
      - :/app
    ports:
      - 5000:5000
    command: python3 app.py
  rasa-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\" --debug"
    ports:
    - '5005:5005'
    public: true
    networks:
    - all

  rasa-actions-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./static:/app/static
    - ./templates:/app/templates
    command: "rasa run actions"
    ports:
    - '5055:5055'
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
      com.docker.network.enable_ipv4: "true"
