version: '3.4'
services:

  duckling-server:
    image: rasa/duckling:latest
    ports:
    - '8000:8000'
    public: true
    networks:
    - all


  rasa-server:
    image: rasa/rasa:1.10.3
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    command: "rasa train && rasa run --enable-api --cors \"*\" --debug"
    ports:
    - '5005:5005'
    public: true
    networks:
    - all
    

  rasa-actions-server:
    image: rasa/rasa_sdk:1.10.1
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    command: "rasa run actions"
    ports:
    - '5055:5055'
    public: true
    networks:
    - all

  rasa-flask:
    image: rasa/rasa:1.10.3
    working_dir: /flask
    build: "./"
    restart: always
    volumes: 
    - ./flask:/flask
    - ./static:/flask/static
    - ./templates:/flask/templates
    - ./actions:/app/actions
    - ./data:/app/data
    command: "python /flask/app.py"
    ports:
    - '5000:5000'
    public: true
    networks:
    - all
